// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: medal.proto

package medal_server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type GetMedalListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserDid string `protobuf:"bytes,1,opt,name=UserDid,proto3" json:"UserDid,omitempty"`
}

func (x *GetMedalListReq) Reset() {
	*x = GetMedalListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalListReq) ProtoMessage() {}

func (x *GetMedalListReq) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalListReq.ProtoReflect.Descriptor instead.
func (*GetMedalListReq) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{0}
}

func (x *GetMedalListReq) GetUserDid() string {
	if x != nil {
		return x.UserDid
	}
	return ""
}

// The response message containing the greetings
type GetMedalListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode int32      `protobuf:"varint,1,opt,name=Retcode,proto3" json:"Retcode,omitempty"`
	Message string     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data    *MedalList `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetMedalListResp) Reset() {
	*x = GetMedalListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedalListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedalListResp) ProtoMessage() {}

func (x *GetMedalListResp) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedalListResp.ProtoReflect.Descriptor instead.
func (*GetMedalListResp) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{1}
}

func (x *GetMedalListResp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetMedalListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMedalListResp) GetData() *MedalList {
	if x != nil {
		return x.Data
	}
	return nil
}

type MedalList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MedalInfoList []*MedalInfo `protobuf:"bytes,3,rep,name=MedalInfoList,proto3" json:"MedalInfoList,omitempty"`
}

func (x *MedalList) Reset() {
	*x = MedalList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalList) ProtoMessage() {}

func (x *MedalList) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalList.ProtoReflect.Descriptor instead.
func (*MedalList) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{2}
}

func (x *MedalList) GetMedalInfoList() []*MedalInfo {
	if x != nil {
		return x.MedalInfoList
	}
	return nil
}

type MedalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserDid     string `protobuf:"bytes,1,opt,name=UserDid,proto3" json:"UserDid,omitempty"`
	EventUid    string `protobuf:"bytes,2,opt,name=EventUid,proto3" json:"EventUid,omitempty"`
	Teacher     string `protobuf:"bytes,3,opt,name=Teacher,proto3" json:"Teacher,omitempty"`
	MedalStatus int32  `protobuf:"varint,4,opt,name=MedalStatus,proto3" json:"MedalStatus,omitempty"`
	ChainHash   string `protobuf:"bytes,5,opt,name=ChainHash,proto3" json:"ChainHash,omitempty"`
	ChainStatus int32  `protobuf:"varint,6,opt,name=ChainStatus,proto3" json:"ChainStatus,omitempty"`
}

func (x *MedalInfo) Reset() {
	*x = MedalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedalInfo) ProtoMessage() {}

func (x *MedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_medal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedalInfo.ProtoReflect.Descriptor instead.
func (*MedalInfo) Descriptor() ([]byte, []int) {
	return file_medal_proto_rawDescGZIP(), []int{3}
}

func (x *MedalInfo) GetUserDid() string {
	if x != nil {
		return x.UserDid
	}
	return ""
}

func (x *MedalInfo) GetEventUid() string {
	if x != nil {
		return x.EventUid
	}
	return ""
}

func (x *MedalInfo) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *MedalInfo) GetMedalStatus() int32 {
	if x != nil {
		return x.MedalStatus
	}
	return 0
}

func (x *MedalInfo) GetChainHash() string {
	if x != nil {
		return x.ChainHash
	}
	return ""
}

func (x *MedalInfo) GetChainStatus() int32 {
	if x != nil {
		return x.ChainStatus
	}
	return 0
}

var File_medal_proto protoreflect.FileDescriptor

var file_medal_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x64, 0x22,
	0x6a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x52, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x41, 0x0a, 0x09, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0d, 0x4d, 0x65, 0x64, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0d, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xbd,
	0x01, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4d,
	0x0a, 0x0c, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x64, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x10, 0x5a,
	0x0e, 0x2e, 0x2f, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_medal_proto_rawDescOnce sync.Once
	file_medal_proto_rawDescData = file_medal_proto_rawDesc
)

func file_medal_proto_rawDescGZIP() []byte {
	file_medal_proto_rawDescOnce.Do(func() {
		file_medal_proto_rawDescData = protoimpl.X.CompressGZIP(file_medal_proto_rawDescData)
	})
	return file_medal_proto_rawDescData
}

var file_medal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_medal_proto_goTypes = []interface{}{
	(*GetMedalListReq)(nil),  // 0: api.GetMedalListReq
	(*GetMedalListResp)(nil), // 1: api.GetMedalListResp
	(*MedalList)(nil),        // 2: api.MedalList
	(*MedalInfo)(nil),        // 3: api.MedalInfo
}
var file_medal_proto_depIdxs = []int32{
	2, // 0: api.GetMedalListResp.Data:type_name -> api.MedalList
	3, // 1: api.MedalList.MedalInfoList:type_name -> api.MedalInfo
	0, // 2: api.MedalService.GetMedalList:input_type -> api.GetMedalListReq
	1, // 3: api.MedalService.GetMedalList:output_type -> api.GetMedalListResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_medal_proto_init() }
func file_medal_proto_init() {
	if File_medal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_medal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMedalListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MedalList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MedalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_medal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medal_proto_goTypes,
		DependencyIndexes: file_medal_proto_depIdxs,
		MessageInfos:      file_medal_proto_msgTypes,
	}.Build()
	File_medal_proto = out.File
	file_medal_proto_rawDesc = nil
	file_medal_proto_goTypes = nil
	file_medal_proto_depIdxs = nil
}
