global:
  scrape_interval: 15s      # 抓取数据的间隔，默认为1分钟
  evaluation_interval: 15s  # 评估数据的间隔
  external_labels:
    monitor: 'my-monitor'

# Alertmanager configuration
#alerting:
#  alertmanagers:
#    - static_configs:
#      - targets:
#        - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
#  - ./rules/rules.yml

scrape_configs:
  # prometheus 自身数据的抓取配置
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node_exporter
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9100","node_exporter:9100"]

  # Go 程序数据的抓取配置
  - job_name: go_app_server
    scrape_interval: 10s  # 抓取间隔
    metrics_path: /metrics  # 抓取数据的URL路径
    # scheme defaults to 'http'
    static_configs:
      - targets: ["localhost:8080","app:8080"]
        labels:
          instance: go-eagle
